import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { getItem, setItem } from '../utils/indexedDB';

const LanguageContext = createContext(null);

const LANGUAGES = [
  { id: 'en', label: 'English', nativeLabel: 'English' },
  { id: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
];

const TRANSLATIONS = {
  mr: {
    'Application Flow': 'अर्ज प्रक्रिया',
    'Step {current} of {total}': '{total} पैकी पायरी {current}',
    'FCFS Flat Booking': 'एफसीएफएस फ्लॅट बुकिंग',
    'Section Details': 'विभाग तपशील',
    'All changes are kept in your session as you continue.': 'तुम्ही पुढे जाताना सर्व बदल तुमच्या सत्रात जतन केले जातील.',
    'Back': 'मागे',
    'Save Draft': 'मसुदा जतन करा',
    'Saving...': 'जतन करत आहे...',
    'Save & Continue': 'जतन करा आणि पुढे जा',
    'Language': 'भाषा',
    'Switch to Marathi': 'मराठीमध्ये बदला',
    'Switch to English': 'इंग्रजीमध्ये बदला',
    'Help': 'मदत',
    'Change Theme': 'थीम बदला',
    'My Account': 'माझे खाते',
    'Signed in': 'साइन इन केलेले',
    'Dashboard': 'डॅशबोर्ड',
    'Logout': 'लॉगआउट',
    'Midnight': 'मिडनाईट',
    'Dark mode': 'डार्क मोड',
    'Daylight': 'डेलाईट',
    'Light mode': 'लाइट मोड',
    'MHDC Classic': 'एमएचडीसी क्लासिक',
    'Maroon & white': 'मॅरून आणि पांढरा',
    'Loading your session...': 'तुमचे सत्र लोड करत आहे...',
    'Priority Access': 'प्राधान्य प्रवेश',
    'Explore homes and complete your booking in one guided flow.': 'घरे पाहा आणि एकाच मार्गदर्शित प्रक्रियेत तुमची बुकिंग पूर्ण करा.',
    'Browse featured residences, complete verification, and move from shortlist to booking confirmation from one connected dashboard.': 'निवडक निवासस्थानांची पाहणी करा, पडताळणी पूर्ण करा आणि एका जोडलेल्या डॅशबोर्डमधून शॉर्टलिस्टमधून बुकिंग पुष्टीपर्यंत जा.',
    'Featured Residence': 'निवडक निवासस्थान',
    'Ready to explore': 'पाहणीस तयार',
    'Show {title}': '{title} दाखवा',
    'Enter your mobile number to continue': 'पुढे जाण्यासाठी तुमचा मोबाईल नंबर प्रविष्ट करा',
    'Enter the OTP sent to your mobile': 'तुमच्या मोबाईलवर पाठवलेला ओटीपी प्रविष्ट करा',
    'Use your registered mobile number': 'तुमचा नोंदणीकृत मोबाईल नंबर वापरा',
    'We will send a 6-digit code to verify your access.': 'तुमची पडताळणी करण्यासाठी आम्ही 6 अंकी कोड पाठवू.',
    'Mobile Number': 'मोबाईल नंबर',
    'Enter 10-digit mobile number': '10 अंकी मोबाईल नंबर प्रविष्ट करा',
    'Sending OTP...': 'ओटीपी पाठवत आहे...',
    'Send OTP': 'ओटीपी पाठवा',
    'Verification in progress': 'पडताळणी सुरू आहे',
    'A verification code was sent to +91 {mobile}. Enter it below to continue.': '+91 {mobile} वर पडताळणी कोड पाठवला आहे. पुढे जाण्यासाठी तो खाली प्रविष्ट करा.',
    'Enter OTP': 'ओटीपी प्रविष्ट करा',
    '6-digit OTP': '6 अंकी ओटीपी',
    'OTP sent to +91 {mobile}': '+91 {mobile} वर ओटीपी पाठवला आहे',
    'Verifying...': 'पडताळणी करत आहे...',
    'Verify & Login': 'पडताळा आणि लॉगिन करा',
    "Didn't receive OTP? Resend": 'ओटीपी मिळाला नाही? पुन्हा पाठवा',
    'Change mobile number': 'मोबाईल नंबर बदला',
    'By continuing, you agree to our Terms & Conditions': 'पुढे चालू ठेवून, तुम्ही आमच्या अटी व शर्ती मान्य करता',
    'Please enter a valid 10-digit mobile number': 'कृपया वैध 10 अंकी मोबाईल नंबर प्रविष्ट करा',
    'Please enter the 6-digit OTP': 'कृपया 6 अंकी ओटीपी प्रविष्ट करा',
    'OTP resent successfully!': 'ओटीपी यशस्वीरित्या पुन्हा पाठवला गेला!',
    'New User': 'नवीन वापरकर्ता',
    'KYC Verification': 'केवायसी पडताळणी',
    'Important': 'महत्त्वाचे',
    'Please enter your PAN and Aadhaar details as per official documents.': 'कृपया अधिकृत कागदपत्रांनुसार तुमचे पॅन आणि आधार तपशील भरा.',
    'Full Name as per PAN': 'पॅननुसार पूर्ण नाव',
    'Enter your full name': 'तुमचे पूर्ण नाव प्रविष्ट करा',
    'Date of Birth': 'जन्मतारीख',
    'PAN Number': 'पॅन क्रमांक',
    'Aadhaar Number': 'आधार क्रमांक',
    'Note:': 'टीप:',
    'Your KYC details will be verified with the respective government databases. Please ensure all information is accurate to avoid rejection.': 'तुमचे केवायसी तपशील संबंधित शासकीय डेटाबेसमधून पडताळले जातील. नकार टाळण्यासाठी सर्व माहिती अचूक असल्याची खात्री करा.',
    'Full name is required': 'पूर्ण नाव आवश्यक आहे',
    'Enter a valid PAN number (e.g., ABCDE1234F)': 'वैध पॅन क्रमांक प्रविष्ट करा (उदा., ABCDE1234F)',
    'Enter a valid 12-digit Aadhaar number': 'वैध 12 अंकी आधार क्रमांक प्रविष्ट करा',
    'Date of birth is required': 'जन्मतारीख आवश्यक आहे',
    'Bank Details': 'बँक तपशील',
    'Bank Account for Refund': 'परताव्यासाठी बँक खाते',
    'This account will be used for refund of EMD if applicable.': 'लागू असल्यास ईएमडी परताव्यासाठी हे खाते वापरले जाईल.',
    'Bank Name': 'बँकेचे नाव',
    'Enter bank name': 'बँकेचे नाव प्रविष्ट करा',
    'Branch Name': 'शाखेचे नाव',
    'Enter branch name': 'शाखेचे नाव प्रविष्ट करा',
    'Account Number': 'खाते क्रमांक',
    'Enter account number': 'खाते क्रमांक प्रविष्ट करा',
    'Confirm Account Number': 'खाते क्रमांकाची पुष्टी करा',
    'Confirm account number': 'खाते क्रमांक पुन्हा प्रविष्ट करा',
    'IFSC Code': 'आयएफएससी कोड',
    'Account Holder Name': 'खातेधारकाचे नाव',
    'Enter account holder name': 'खातेधारकाचे नाव प्रविष्ट करा',
    'Bank name is required': 'बँकेचे नाव आवश्यक आहे',
    'Enter a valid account number': 'वैध खाते क्रमांक प्रविष्ट करा',
    'Account numbers do not match': 'खाते क्रमांक जुळत नाहीत',
    'Enter a valid 11-character IFSC code': 'वैध 11 अक्षरी आयएफएससी कोड प्रविष्ट करा',
    'Account holder name is required': 'खातेधारकाचे नाव आवश्यक आहे',
    'PMAY Eligibility Check': 'पीएमएवाय पात्रता तपासणी',
    'PMAY Subsidy Scheme': 'पीएमएवाय अनुदान योजना',
    'Answer the questions below to check whether you qualify for PMAY subsidy.': 'तुम्ही पीएमएवाय अनुदानासाठी पात्र आहात का हे तपासण्यासाठी खालील प्रश्नांची उत्तरे द्या.',
    'What is your monthly household income?': 'तुमचे मासिक कुटुंबीय उत्पन्न किती आहे?',
    'Below Rs. 25,000': 'रु. 25,000 पेक्षा कमी',
    'Rs. 25,000 to Rs. 50,000': 'रु. 25,000 ते रु. 50,000',
    'Above Rs. 50,000': 'रु. 50,000 पेक्षा जास्त',
    'Do you already own a pucca house?': 'तुमच्या नावावर आधीपासून पक्के घर आहे का?',
    'Yes': 'होय',
    'No': 'नाही',
    'Checking Eligibility...': 'पात्रता तपासत आहे...',
    'Check Eligibility': 'पात्रता तपासा',
    'Eligible for Non-PMAY Booking': 'नॉन-पीएमएवाय बुकिंगसाठी पात्र',
    'Applicants who already own a pucca house can continue with the non-PMAY booking option only.': 'ज्यांच्याकडे आधीपासून पक्के घर आहे ते फक्त नॉन-पीएमएवाय बुकिंग पर्यायासह पुढे जाऊ शकतात.',
    'Non-PMAY Only': 'फक्त नॉन-पीएमएवाय',
    'Applicants with monthly income above Rs. 50,000 can continue with the non-PMAY booking option only.': 'ज्यांचे मासिक उत्पन्न रु. 50,000 पेक्षा जास्त आहे ते फक्त नॉन-पीएमएवाय पर्यायासह पुढे जाऊ शकतात.',
    'Eligible for PMAY and Non-PMAY': 'पीएमएवाय आणि नॉन-पीएमएवाय दोन्हीसाठी पात्र',
    'You can choose either PMAY or Non-PMAY to continue.': 'पुढे जाण्यासाठी तुम्ही पीएमएवाय किंवा नॉन-पीएमएवाय यापैकी एक निवडू शकता.',
    'EWS/LIG - Eligible for PMAY and Non-PMAY': 'ईडब्ल्यूएस/एलआयजी - पीएमएवाय आणि नॉन-पीएमएवाय दोन्हीसाठी पात्र',
    'MIG-I - Eligible for PMAY and Non-PMAY': 'एमआयजी-I - पीएमएवाय आणि नॉन-पीएमएवाय दोन्हीसाठी पात्र',
    'Select one option to continue': 'पुढे जाण्यासाठी एक पर्याय निवडा',
    'Your next steps will follow the scheme you choose here.': 'तुमची पुढील पायरी येथे निवडलेल्या योजनेनुसार असेल.',
    'Continue with PMAY': 'पीएमएवायसह पुढे जा',
    'Continue with Non-PMAY': 'नॉन-पीएमएवायसह पुढे जा',
    'Personal Details': 'वैयक्तिक तपशील',
    'Gender': 'लिंग',
    'Select Gender': 'लिंग निवडा',
    'Male': 'पुरुष',
    'Female': 'महिला',
    'Other': 'इतर',
    'Marital Status': 'वैवाहिक स्थिती',
    'Select Marital Status': 'वैवाहिक स्थिती निवडा',
    'Single': 'अविवाहित',
    'Married': 'विवाहित',
    'Divorced': 'घटस्फोटित',
    'Widowed': 'विधवा/विधुर',
    'Email Address': 'ईमेल पत्ता',
    'Nationality': 'राष्ट्रीयत्व',
    'Address': 'पत्ता',
    'Enter your full address': 'तुमचा पूर्ण पत्ता प्रविष्ट करा',
    'City': 'शहर',
    'Enter city': 'शहर प्रविष्ट करा',
    'State': 'राज्य',
    'Enter state': 'राज्य प्रविष्ट करा',
    'Pincode': 'पिनकोड',
    'Gender is required': 'लिंग आवश्यक आहे',
    'Marital status is required': 'वैवाहिक स्थिती आवश्यक आहे',
    'Valid email is required': 'वैध ईमेल आवश्यक आहे',
    'Address is required': 'पत्ता आवश्यक आहे',
    'City is required': 'शहर आवश्यक आहे',
    'State is required': 'राज्य आवश्यक आहे',
    'Valid 6-digit pincode is required': 'वैध 6 अंकी पिनकोड आवश्यक आहे',
    'Indian': 'भारतीय',
    'Employment Details': 'रोजगार तपशील',
    'Employment Type': 'रोजगार प्रकार',
    'Salaried': 'पगारदार',
    'Self Employed': 'स्वयंरोजगार',
    'Business': 'व्यवसाय',
    'Retired': 'निवृत्त',
    'Employer Name': 'नियोक्त्याचे नाव',
    'Company name': 'कंपनीचे नाव',
    'Designation': 'पदनाम',
    'Your designation': 'तुमचे पदनाम',
    'Business Name': 'व्यवसायाचे नाव',
    'Business name': 'व्यवसायाचे नाव',
    'Nature of Business': 'व्यवसायाचे स्वरूप',
    'Business type': 'व्यवसायाचा प्रकार',
    'Monthly Income (₹)': 'मासिक उत्पन्न (₹)',
    'Enter monthly income': 'मासिक उत्पन्न प्रविष्ट करा',
    'Work Experience (Years)': 'कामाचा अनुभव (वर्षे)',
    'Select Experience': 'अनुभव निवडा',
    '0-1 Years': '0-1 वर्षे',
    '1-3 Years': '1-3 वर्षे',
    '3-5 Years': '3-5 वर्षे',
    '5-10 Years': '5-10 वर्षे',
    '10+ Years': '10+ वर्षे',
    'Employment type is required': 'रोजगार प्रकार आवश्यक आहे',
    'Monthly income is required': 'मासिक उत्पन्न आवश्यक आहे',
    'Category Selection': 'श्रेणी निवड',
    'Category Reservation': 'श्रेणी आरक्षण',
    'Select your category as per your caste certificate. This will determine your quota.': 'तुमच्या जातीच्या प्रमाणपत्रानुसार तुमची श्रेणी निवडा. यावर तुमचा कोटा ठरेल.',
    'Select Category': 'श्रेणी निवडा',
    'General': 'सामान्य',
    'Open category': 'मुक्त श्रेणी',
    'OBC': 'ओबीसी',
    'Other Backward Classes': 'इतर मागासवर्ग',
    'SC': 'एससी',
    'Scheduled Caste': 'अनुसूचित जाती',
    'ST': 'एसटी',
    'Scheduled Tribe': 'अनुसूचित जमाती',
    'EWS': 'ईडब्ल्यूएस',
    'Economically Weaker Section': 'आर्थिकदृष्ट्या दुर्बल घटक',
    'Please select a category': 'कृपया श्रेणी निवडा',
    'I have a valid caste certificate': 'माझ्याकडे वैध जातीचे प्रमाणपत्र आहे',
    'I have a valid income certificate (income below ₹8 Lakhs)': 'माझ्याकडे वैध उत्पन्न प्रमाणपत्र आहे (उत्पन्न ₹8 लाखांपेक्षा कमी)',
    'Co-Applicant Details': 'सह-अर्जदार तपशील',
    'Do you want to add a co-applicant?': 'तुम्हाला सह-अर्जदार जोडायचा आहे का?',
    'Yes, Add Co-Applicant': 'होय, सह-अर्जदार जोडा',
    'Joint ownership': 'संयुक्त मालकी',
    'No, Single Applicant': 'नाही, एकल अर्जदार',
    'Individual ownership': 'वैयक्तिक मालकी',
    'Co-Applicant Name': 'सह-अर्जदाराचे नाव',
    'Enter co-applicant name': 'सह-अर्जदाराचे नाव प्रविष्ट करा',
    'Relationship': 'नाते',
    'Select Relationship': 'नाते निवडा',
    'Spouse': 'पती/पत्नी',
    'Parent': 'पालक',
    'Sibling': 'भाऊ/बहिण',
    'Child': 'मूल',
    'Mobile Number': 'मोबाईल नंबर',
    'Upload Documents': 'कागदपत्रे अपलोड करा',
    'Document Requirements': 'कागदपत्र आवश्यकता',
    'Upload clear, legible copies of all required documents. Max file size: 5MB. Supported formats: JPG, PNG, PDF.': 'सर्व आवश्यक कागदपत्रांच्या स्पष्ट व वाचनीय प्रती अपलोड करा. कमाल फाईल आकार: 5MB. समर्थित फॉरमॅट: JPG, PNG, PDF.',
    'Passport Photo': 'पासपोर्ट फोटो',
    'Signature': 'स्वाक्षरी',
    'PAN Card': 'पॅन कार्ड',
    'Aadhaar Card (Front)': 'आधार कार्ड (समोरची बाजू)',
    'Aadhaar Card (Back)': 'आधार कार्ड (मागील बाजू)',
    'Aadhaar Front': 'आधार समोरची बाजू',
    'Aadhaar Back': 'आधार मागील बाजू',
    'Income Certificate': 'उत्पन्न प्रमाणपत्र',
    'Bank Passbook/Cancelled Cheque': 'बँक पासबुक/रद्द चेक',
    'Please upload all required documents': 'कृपया सर्व आवश्यक कागदपत्रे अपलोड करा',
    'Uploading...': 'अपलोड करत आहे...',
    'Uploaded successfully': 'यशस्वीरित्या अपलोड झाले',
    'Click to upload': 'अपलोड करण्यासाठी क्लिक करा',
    'JPG, PNG, PDF up to 5MB': 'JPG, PNG, PDF 5MB पर्यंत',
    'Review & Submit': 'पुनरावलोकन आणि सबमिट',
    'Please review all details before submitting': 'सबमिट करण्यापूर्वी सर्व तपशील तपासा',
    'Once submitted, you cannot make changes. Contact support for corrections.': 'सबमिट केल्यानंतर तुम्ही बदल करू शकत नाही. दुरुस्त्यांसाठी सहाय्यकांशी संपर्क साधा.',
    'KYC Details': 'केवायसी तपशील',
    'PMAY Eligibility': 'पीएमएवाय पात्रता',
    'Category': 'श्रेणी',
    'Documents': 'कागदपत्रे',
    'Applicant Photo': 'अर्जदाराचा फोटो',
    'Applicant passport photograph': 'अर्जदाराचा पासपोर्ट फोटो',
    'Completed': 'पूर्ण',
    'Pending': 'प्रलंबित',
    'Done': 'झाले',
    'Full Name': 'पूर्ण नाव',
    'Uploaded At': 'अपलोड तारीख',
    'I declare that all the information provided by me is true and accurate. I have read and understood the terms and conditions of the FCFS Flat Booking Scheme.': 'मी घोषित करतो/करते की मी दिलेली सर्व माहिती खरी आणि अचूक आहे. मी एफसीएफएस फ्लॅट बुकिंग योजनेच्या अटी व शर्ती वाचल्या आणि समजल्या आहेत.',
    'EMD Payment': 'ईएमडी पेमेंट',
    'Earnest Money Deposit (EMD)': 'अनामत रक्कम (ईएमडी)',
    'Pay ₹{amount} to proceed with flat selection. This amount will be adjusted in the final payment.': 'फ्लॅट निवडीसाठी पुढे जाण्यासाठी ₹{amount} भरा. ही रक्कम अंतिम पेमेंटमध्ये समायोजित केली जाईल.',
    'EMD Amount': 'ईएमडी रक्कम',
    'Select Payment Method': 'पेमेंट पद्धत निवडा',
    'Net Banking': 'नेट बँकिंग',
    'Debit Card': 'डेबिट कार्ड',
    'Credit Card': 'क्रेडिट कार्ड',
    'Please select a payment method': 'कृपया पेमेंट पद्धत निवडा',
    'Processing Payment...': 'पेमेंट प्रक्रिया सुरू आहे...',
    'Pay ₹{amount}': '₹{amount} भरा',
    'Secure payment powered by Razorpay': 'रेझरपे समर्थित सुरक्षित पेमेंट',
    'Payment Successful!': 'पेमेंट यशस्वी!',
    'Your EMD of ₹{amount} has been received.': 'तुमची ₹{amount} ची ईएमडी प्राप्त झाली आहे.',
    'Redirecting to flat selection...': 'फ्लॅट निवडीकडे वळवत आहे...',
    'Flat Lock': 'फ्लॅट लॉक',
    'No Flat Selected': 'फ्लॅट निवडलेला नाही',
    'Please select a flat to proceed.': 'पुढे जाण्यासाठी कृपया फ्लॅट निवडा.',
    'Go to Flat Selection': 'फ्लॅट निवडीकडे जा',
    'Flat Lock Status': 'फ्लॅट लॉक स्थिती',
    'Flat Locked for 24 Hours': 'फ्लॅट 24 तासांसाठी लॉक आहे',
    'Complete your confirmation payment before the timer expires.': 'टायमर संपण्यापूर्वी पुष्टी पेमेंट पूर्ण करा.',
    'Time Remaining': 'उर्वरित वेळ',
    'Locked Flat Details': 'लॉक केलेल्या फ्लॅटचे तपशील',
    'Flat Number': 'फ्लॅट क्रमांक',
    'Type': 'प्रकार',
    'Area': 'क्षेत्रफळ',
    'Price': 'किंमत',
    'Cancel Booking': 'बुकिंग रद्द करा',
    'Proceed to Payment': 'पेमेंटसाठी पुढे जा',
    'Expired': 'कालबाह्य',
    'Are you sure you want to cancel? Your EMD will be forfeited.': 'तुम्हाला नक्की रद्द करायचे आहे का? तुमची ईएमडी जप्त केली जाईल.',
    'Confirmation Payment': 'पुष्टी पेमेंट',
    'Please select a flat first.': 'कृपया प्रथम फ्लॅट निवडा.',
    'Final Payment': 'अंतिम पेमेंट',
    'Pay the remaining amount to confirm your booking.': 'तुमची बुकिंग पुष्टी करण्यासाठी उर्वरित रक्कम भरा.',
    'Payment Summary': 'पेमेंट सारांश',
    'Flat Price ({id})': 'फ्लॅट किंमत ({id})',
    'EMD Paid': 'ईएमडी भरलेली',
    'Balance Due': 'बाकी देय',
    'Your booking has been confirmed!': 'तुमची बुकिंग पुष्टी झाली आहे!',
    'Redirecting...': 'वळवत आहे...',
    'Booking Complete': 'बुकिंग पूर्ण',
    'Booking Confirmed': 'बुकिंग पुष्टी',
    'Your flat has been successfully reserved in the FCFS booking flow.': 'एफसीएफएस बुकिंग प्रक्रियेत तुमचा फ्लॅट यशस्वीरित्या राखीव ठेवला गेला आहे.',
    'Total Price': 'एकूण किंमत',
    'Booking Date': 'बुकिंग तारीख',
    'Application ID': 'अर्ज आयडी',
    'Next Actions': 'पुढील कृती',
    'Everything is ready.': 'सर्व काही तयार आहे.',
    'A confirmation email has been sent to your registered address. You can now download your receipt or return to the dashboard.': 'तुमच्या नोंदणीकृत पत्त्यावर पुष्टी ईमेल पाठवला आहे. आता तुम्ही पावती डाउनलोड करू शकता किंवा डॅशबोर्डवर परत जाऊ शकता.',
    'Receipt generated': 'पावती तयार झाली',
    'Your payment and booking details are ready to export.': 'तुमचे पेमेंट आणि बुकिंग तपशील निर्यात करण्यासाठी तयार आहेत.',
    'Share your confirmation': 'तुमची पुष्टी शेअर करा',
    'Send your booking summary to family members or keep it for records.': 'तुमचा बुकिंग सारांश कुटुंबीयांना पाठवा किंवा नोंदींसाठी जतन करा.',
    'Download Receipt': 'पावती डाउनलोड करा',
    'Share Confirmation': 'पुष्टी शेअर करा',
    'Go to Dashboard': 'डॅशबोर्डवर जा',
    'Application Dashboard': 'अर्ज डॅशबोर्ड',
    'Track every verified step, upload status, and booking milestone in one place.': 'सर्व पडताळलेल्या पायऱ्या, अपलोड स्थिती आणि बुकिंग टप्पे एका ठिकाणी पाहा.',
    'Last updated:': 'शेवटचे अद्यतन:',
    'Applicant ID: {id}': 'अर्जदार आयडी: {id}',
    'Age: 35 | Mobile: +91 {mobile}': 'वय: 35 | मोबाईल: +91 {mobile}',
    'Registration No.': 'नोंदणी क्र.',
    'Registration & Eligibility': 'नोंदणी आणि पात्रता',
    'In progress': 'प्रक्रिया सुरू',
    'Applicant Details': 'अर्जदार तपशील',
    'Documents & Review': 'कागदपत्रे आणि पुनरावलोकन',
    'Flat Booking': 'फ्लॅट बुकिंग',
    'Primary Applicant': 'मुख्य अर्जदार',
    'Email': 'ईमेल',
    'Not selected': 'निवडलेले नाही',
    'Uploaded Documents': 'अपलोड केलेली कागदपत्रे',
    'Preferred Flat': 'प्राधान्य फ्लॅट',
    'Lock Status': 'लॉक स्थिती',
    'Locked': 'लॉक केलेले',
    'Awaiting selection': 'निवडीची प्रतीक्षा',
    'Booking': 'बुकिंग',
    'Confirmed': 'पुष्टी',
    'Not confirmed': 'पुष्टी नाही',
    'Not checked': 'तपासलेले नाही',
    'your@email.com': 'your@email.com',
    'Confirmation & Booking': 'पुष्टी आणि बुकिंग',
    'Co-Applicant': 'सह-अर्जदार',
    'FCFS Booking Portal': 'एफसीएफएस बुकिंग पोर्टल',
    'Alerts': 'सूचना',
    'Notifications': 'अधिसूचना',
    'Action required': 'कृती आवश्यक',
    'Please complete {step} to continue your application.': 'तुमचा अर्ज पुढे सुरू ठेवण्यासाठी कृपया {step} पूर्ण करा.',
    'Snapshot': 'झटपट सारांश',
    'Application Summary': 'अर्ज सारांश',
    'User mobile': 'वापरकर्ता मोबाईल',
    'Current step': 'सध्याची पायरी',
    'Flat selected': 'फ्लॅट निवडलेला',
    'Booking confirmed': 'बुकिंग पुष्टी',
    'Find your dream flat': 'तुमचा स्वप्नातील फ्लॅट शोधा',
    'Choose Project': 'प्रकल्प निवडा',
    'Open': 'उपलब्ध',
    'Hover or click a project marker on the map to see details here.': 'तपशील पाहण्यासाठी नकाशावरील प्रकल्प चिन्हावर होवर करा किंवा क्लिक करा.',
    'Best Fit': 'सर्वोत्तम पर्याय',
    'Commute': 'प्रवास',
    'Select Your Unit': 'तुमचे युनिट निवडा',
    'Building': 'इमारत',
    '{count} open': '{count} उपलब्ध',
    'Floor': 'मजला',
    'Filters': 'फिल्टर्स',
    'Budget': 'अंदाजपत्रक',
    'Floor Band': 'मजला श्रेणी',
    'All floors': 'सर्व मजले',
    'Low (1-3)': 'खालचे (1-3)',
    'Mid (4-7)': 'मध्यम (4-7)',
    'High (8-10)': 'वरचे (8-10)',
    'Area Type': 'क्षेत्र प्रकार',
    'All': 'सर्व',
    'Compact ≤650': 'कंपॅक्ट ≤650',
    'Family 650-850': 'कुटुंब 650-850',
    'Premium 850+': 'प्रिमियम 850+',
    'Tower': 'टॉवर',
    '{count} units': '{count} युनिट्स',
    'Selected': 'निवडलेले',
    'Available': 'उपलब्ध',
    'Held': 'राखीव',
    'Sold': 'विकलेले',
    'No units match your filters.': 'तुमच्या फिल्टर्सनुसार कोणतेही युनिट उपलब्ध नाही.',
    'Booking Summary': 'बुकिंग सारांश',
    'Reservation Timer': 'आरक्षण टायमर',
    'Timer expired — please select again.': 'टायमर संपला आहे — कृपया पुन्हा निवडा.',
    'Unit held while you review.': 'तुम्ही तपासत असताना युनिट राखीव ठेवले आहे.',
    'Select a unit to start timer.': 'टायमर सुरू करण्यासाठी युनिट निवडा.',
    'Project': 'प्रकल्प',
    'Selected Flat': 'निवडलेला फ्लॅट',
    'Facing': 'दिशा',
    'Status': 'स्थिती',
    'Ready to reserve': 'आरक्षणासाठी तयार',
    'Select a green unit to see details.': 'तपशील पाहण्यासाठी हिरवे युनिट निवडा.',
    'Guide': 'मार्गदर्शक',
    'Reserving…': 'राखीव करत आहे…',
    'Timer Expired': 'टायमर संपला',
    'Confirm & Pay': 'पुष्टी करा आणि भरा',
    'Expanded Floor Plan': 'विस्तारित फ्लोअर प्लॅन',
    'CORRIDOR': 'कॉरिडॉर',
    'LIFT': 'लिफ्ट',
    'ACTIVE': 'सक्रिय',
    'sq.ft': 'चौ.फुट',
    'East Facing': 'पूर्वाभिमुख',
    'West Facing': 'पश्चिमाभिमुख',
    '1 BHK': '1 बीएचके',
    '2 BHK': '2 बीएचके',
    '3 BHK': '3 बीएचके',
    'MIHAN Smart Township': 'मिहान स्मार्ट टाउनशिप',
    'Manish Nagar Heights': 'मनीष नगर हाइट्स',
    'Wardha Road Residency': 'वर्धा रोड रेसिडेन्सी',
    'Trimurti Nagar Square': 'त्रिमूर्ती नगर स्क्वेअर',
    'Hingna Hills Enclave': 'हिंगणा हिल्स एन्क्लेव्ह',
    'Dharampeth Urban Homes': 'धरमपेठ अर्बन होम्स',
    'Sadar Cantonment Greens': 'सदर कॅन्टोनमेंट ग्रीन्स',
    'Koradi Road Meadows': 'कोराडी रोड मेडोज',
    'Metro City Grand Township': 'मेट्रो सिटी ग्रँड टाउनशिप',
    'Dharampeth': 'धरमपेठ',
    'Sadar': 'सदर',
    'Civil Lines': 'सिव्हिल लाइन्स',
    'Sitabuldi': 'सिताबर्डी',
    'Laxmi Nagar': 'लक्ष्मी नगर',
    'Manish Nagar': 'मनीष नगर',
    'Wardha Road': 'वर्धा रोड',
    'MIHAN': 'मिहान',
    'Hingna': 'हिंगणा',
    'Koradi': 'कोराडी',
    'Besa': 'बेसा',
    'Trimurti Ngr': 'त्रिमूर्ती नगर',
    'NAGPUR': 'नागपूर',
    'N': 'उ',
    '~5 km': '~5 कि.मी.',
    'Airport corridor access with strong future growth potential.': 'विमानतळ कॉरिडॉरला जलद प्रवेश आणि भविष्यातील वाढीची मजबूत संधी.',
    'Best for buyers prioritising future appreciation and city-edge access.': 'भविष्यातील मूल्यवाढ आणि शहराच्या काठावरील प्रवेशाला प्राधान्य देणाऱ्या खरेदीदारांसाठी उत्तम.',
    'Approx. 12 mins to airport and MIHAN business district.': 'विमानतळ आणि मिहान व्यावसायिक जिल्ह्यापर्यंत अंदाजे 12 मिनिटे.',
    'Balanced family-oriented address with strong everyday convenience.': 'दररोजच्या सोयींसह संतुलित कुटुंबकेंद्री स्थान.',
    'Great for applicants who want practical daily living with strong connectivity.': 'मजबूत कनेक्टिव्हिटीसह व्यावहारिक दैनंदिन जीवन इच्छिणाऱ्या अर्जदारांसाठी योग्य.',
    'Quick Wardha Road access and close retail catchment.': 'वर्धा रोडला जलद प्रवेश आणि जवळपासचे रिटेल क्षेत्र.',
    'Well-connected corridor project for city-wide movement.': 'संपूर्ण शहरात सहज प्रवासासाठी उत्तम कनेक्टिव्हिटी असलेला कॉरिडॉर प्रकल्प.',
    'Ideal for working professionals who need reliable cross-city access.': 'शहरभर विश्वासार्ह प्रवासाची गरज असलेल्या कामकाजी व्यक्तींसाठी आदर्श.',
    'Strong arterial access toward central business and transit routes.': 'मध्यवर्ती व्यावसायिक आणि वाहतूक मार्गांकडे मजबूत प्रवेश.',
    'Central residential cluster with schools and services nearby.': 'शाळा आणि सेवा जवळ असलेला मध्यवर्ती निवासी समूह.',
    'A smart fit for applicants wanting a central, established neighborhood.': 'मध्यवर्ती आणि स्थापित परिसर इच्छिणाऱ्या अर्जदारांसाठी उत्तम पर्याय.',
    'Smooth mid-city connectivity for schools, offices, and markets.': 'शाळा, कार्यालये आणि बाजारांसाठी मध्यम-शहर कनेक्टिव्हिटी.',
    'Calmer west-side project with more breathing room and open edges.': 'अधिक मोकळ्या जागेसह शांत पश्चिम भागातील प्रकल्प.',
    'Suited to buyers looking for quieter surroundings and practical layouts.': 'शांत परिसर आणि व्यावहारिक आराखडे शोधणाऱ्या खरेदीदारांसाठी योग्य.',
    'Convenient west-side movement toward industrial and work belts.': 'औद्योगिक आणि कामाच्या पट्ट्यांकडे सोयीस्कर पश्चिमेकडील प्रवास.',
    'Premium city-core project with high convenience value.': 'उच्च सोयीसुविधांसह प्रीमियम शहर-मध्य प्रकल्प.',
    'Premium pick for applicants who want a central city address.': 'मध्यवर्ती शहरातील पत्ता इच्छिणाऱ्या अर्जदारांसाठी प्रीमियम निवड.',
    'Fast access to civic, medical, and retail zones.': 'नागरी, वैद्यकीय आणि किरकोळ क्षेत्रांना जलद प्रवेश.',
    'Leafier north-central project with established surroundings.': 'स्थापित परिसरासह अधिक हिरवळ असलेला उत्तर-मध्य प्रकल्प.',
    'Strong choice for buyers who value mature localities and daily convenience.': 'स्थापित परिसर आणि दैनंदिन सोयींना महत्त्व देणाऱ्या खरेदीदारांसाठी चांगला पर्याय.',
    'Reliable road network with strong north-central connectivity.': 'मजबूत उत्तर-मध्य कनेक्टिव्हिटीसह विश्वासार्ह रस्ते जाळे.',
    'Growth-corridor inventory with value-upside positioning.': 'मूल्यवाढीच्या संधींसह ग्रोथ-कॉरिडॉर इन्व्हेंटरी.',
    'Good for long-term value seekers looking in expansion corridors.': 'विस्तार कॉरिडॉरमध्ये दीर्घकालीन मूल्य शोधणाऱ्यांसाठी योग्य.',
    'North-bound movement toward emerging development belts.': 'उदयोन्मुख विकास पट्ट्यांकडे उत्तर दिशेने प्रवास.',
    'Large-format township inventory with multiple towers, amenities, and phased releases.': 'अनेक टॉवर्स, सुविधा आणि टप्प्याटप्प्याने उपलब्ध इन्व्हेंटरी असलेली मोठ्या स्वरूपाची टाउनशिप.',
    'Best for applicants comparing many tower options inside one integrated township.': 'एका एकात्मिक टाउनशिपमध्ये अनेक टॉवर पर्याय तुलना करणाऱ्यांसाठी उत्तम.',
    'Strong ring-road connectivity with room for future infrastructure growth.': 'भविष्यातील पायाभूत वाढीसह मजबूत रिंग रोड कनेक्टिव्हिटी.',
    'Wardha Road Residences': 'वर्धा रोड रेसिडेन्सेस',
    'Civil Lines Homes': 'सिव्हिल लाइन्स होम्स',
    'Besa Smart Living': 'बेसा स्मार्ट लिव्हिंग',
    'Manish Nagar Heights': 'मनीष नगर हाइट्स',
    'Trimurti Nagar Homes': 'त्रिमूर्ती नगर होम्स',
    'Pratap Nagar Residences': 'प्रतापनगर रेसिडेन्सेस',
    'Shankar Nagar Living': 'शंकर नगर लिव्हिंग',
    'Friends Colony Homes': 'फ्रेंड्स कॉलनी होम्स',
    'Laxmi Nagar Towers': 'लक्ष्मी नगर टॉवर्स',
    'Dharampeth Residences': 'धरमपेठ रेसिडेन्सेस',
    'Sadar Urban Homes': 'सदर अर्बन होम्स',
    'Premium apartment towers inspired by Nagpur growth corridors and family-focused layouts.': 'नागपूरच्या वाढीच्या कॉरिडॉर्सपासून प्रेरित प्रीमियम अपार्टमेंट टॉवर्स आणि कुटुंबकेंद्री आराखडे.',
    'Elegant urban residences with landscaped arrival courts and contemporary facade design.': 'सुशोभित प्रवेश भाग आणि आधुनिक फ्रंट डिझाइनसह आकर्षक शहरी निवासस्थान.',
    'Modern homes shaped for everyday comfort, clean circulation, and easy booking discovery.': 'दररोजच्या आराम, स्वच्छ हालचाल आणि सोप्या बुकिंग अनुभवासाठी तयार आधुनिक घरे.',
    'Warm residential towers designed for compact family living and quick city access.': 'लहान कुटुंबांसाठी आरामदायी जीवन आणि शहरात जलद प्रवेशासाठी डिझाइन केलेले निवासी टॉवर्स.',
    'Bright apartment blocks with practical layouts, balconies, and neighborhood connectivity.': 'व्यावहारिक आराखडे, बाल्कनी आणि परिसर कनेक्टिव्हिटी असलेले उजळ अपार्टमेंट ब्लॉक्स.',
    'Urban homes with modern fronts, visitor lounges, and landscaped setbacks.': 'आधुनिक फ्रंट, भेट देणाऱ्यांसाठी लाउंज आणि सुशोभित सेटबॅक असलेली शहरी घरे.',
    'Refined residential clusters built around comfort, daylight, and smooth daily movement.': 'आराम, नैसर्गिक प्रकाश आणि सोयीस्कर दैनंदिन हालचालीभोवती तयार केलेले परिष्कृत निवासी समूह.',
    'Contemporary mid-rise apartments with calm entry courts and premium family spaces.': 'शांत प्रवेश भाग आणि प्रीमियम कौटुंबिक जागांसह आधुनिक मध्यम उंचीची अपार्टमेंट्स.',
    'Elegant housing options with strong street presence and efficient floor plans.': 'रस्त्यावर ठळक उपस्थिती आणि कार्यक्षम फ्लोअर प्लॅनसह आकर्षक निवास पर्याय.',
    'Premium apartment living with elevated interiors and a polished neighborhood experience.': 'उत्कृष्ट अंतर्गत रचना आणि दर्जेदार परिसर अनुभवासह प्रीमियम अपार्टमेंट जीवन.',
    'Fresh residential inventory with strong accessibility and aspirational community appeal.': 'उत्कृष्ट प्रवेशसुविधा आणि आकर्षक समुदाय अनुभवासह नवीन निवासी इन्व्हेंटरी.',
    'Login': 'लॉगिन',
    'KYC': 'केवायसी',
    'PMAY Eligibility': 'पीएमएवाय पात्रता',
    'Employment': 'रोजगार',
    'Review': 'पुनरावलोकन',
    'Category & Co-Applicant': 'श्रेणी आणि सह-अर्जदार',
    'Non-PMAY': 'नॉन-पीएमएवाय',
    'Flat Selection': 'फ्लॅट निवड',
    'Booking Confirmed': 'बुकिंग पुष्टी',
  },
};

const interpolate = (message, variables = {}) =>
  Object.entries(variables).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    message,
  );

const DEFAULT_LANGUAGE = 'en';

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(DEFAULT_LANGUAGE);

  // Hydrate from IndexedDB once on mount
  useEffect(() => {
    (async () => {
      try {
        const savedLanguage = await getItem('language');
        if (savedLanguage && LANGUAGES.some((lang) => lang.id === savedLanguage)) {
          setLanguage(savedLanguage);
        }
      } catch (err) {
        console.warn('[LanguageContext] Failed to read language from IndexedDB', err);
      }
    })();
  }, []);

  // Persist to IndexedDB and update DOM lang attribute on change
  useEffect(() => {
    setItem('language', language);
    document.documentElement.lang = language === 'mr' ? 'mr' : 'en';
  }, [language]);

  const value = useMemo(() => {
    const locale = language === 'mr' ? 'mr-IN' : 'en-IN';

    const t = (key, variables) => {
      const message = TRANSLATIONS[language]?.[key] ?? key;
      return interpolate(message, variables);
    };

    return {
      language,
      locale,
      isMarathi: language === 'mr',
      languages: LANGUAGES,
      setLanguage,
      toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'mr' : 'en')),
      t,
      formatDate: (value, options) => new Intl.DateTimeFormat(locale, options).format(new Date(value)),
      formatNumber: (value) => new Intl.NumberFormat(locale).format(value),
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
